---
title: "Percentage of Glance Time (Instrument Cluster) (%)"
author: "Yee Thung Lee"
date: "2025-11-30"
output: html_document
---

## Load Libraries

```{r setup, include=FALSE}
# LOAD LIBRARIES
suppressPackageStartupMessages({
  library(tidyr)
  library(dplyr)
  library (ggplot2)
  library (lmerTest)
  library (emmeans)
  library (lme4)
  library (viridis)
  library (readxl)
})
```

```{r}
# LOAD EXCEL SHEET
# % OF GLANCE TIME
PercentageOfGlanceTimeData <- read_excel(
  "C:\\Users\\tsytl\\OneDrive - University of Leeds\\Paper 2 - Visual Scanning Patterns\\PERCENTAGE OF GLANCE TIME ON EACH AOI.xlsx",
  sheet = "Sheet1"
)

head (PercentageOfGlanceTimeData)
```

## Define Variables for Data Analysis

```{r}
# DEFINE VARIABLE FOR DATA ANALYSIS

# RENAME COLUMNS
PercentageOfGlanceTimeData <- PercentageOfGlanceTimeData %>%
  rename(
    LightingConditions = `Lighting Conditions`,
    AutomationLevel = `Automation Level`,
    SubNum = `Sub Number`,
    RunNum = `Run Number`,
    PercentageOfGlanceInstrumentCluster = `Percentage of Glance Time (Instrument Cluster) (%)`
  )

# DEFINE COLUMNS AS FACTOR (SUBJECT ID, RUN NUMBER,INDEPENDENT VARIABLES)
PercentageOfGlanceTimeData$SubNum <- factor (PercentageOfGlanceTimeData$SubNum)
PercentageOfGlanceTimeData$RunNum <- factor (PercentageOfGlanceTimeData$RunNum)
PercentageOfGlanceTimeData$LightingConditions <- factor (PercentageOfGlanceTimeData$LightingConditions)
PercentageOfGlanceTimeData$AutomationLevel <- factor (PercentageOfGlanceTimeData$AutomationLevel)


# DEFINE COLUMNS AS DEPENDENT VARIABLES (% GLANCE TIME ON ROAD)
str(PercentageOfGlanceTimeData$PercentageOfGlanceInstrumentCluster)
PercentageOfGlanceTimeData$PercentageOfGlanceInstrumentCluster<- as.numeric(PercentageOfGlanceTimeData$PercentageOfGlanceInstrumentCluster) 
```

```{r}
library(glmmTMB)

# FINAL MODEL
# LIGHT, AUTOMATION, LIGHT*AUTOMATION

glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster <- glmmTMB(PercentageOfGlanceInstrumentCluster~ LightingConditions + AutomationLevel + LightingConditions*AutomationLevel + (1|SubNum), family = tweedie(link = "log"), data = PercentageOfGlanceTimeData)

summary (glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster)
```

```{r}
library (performance)
# CALCULATE R-SQUARED VALUES 
r2_values <- r2(glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster)
print (r2_values)
```


### Post-Hoc Comparison

#### Lighting of the Driving Environment

```{r}

# OBTAIN ESTIMATED MARGINAL MEANS (LIGHTING) - PAIRWISE 
lighting_emmeans <- emmeans (glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster, ~ LightingConditions)
lighting_emmeans
# PAIRWISE
pairwise_lighting <- pairs (lighting_emmeans, adjust = "bonferroni")
pairwise_lighting

```

#### Level of Automation

```{r}
# OBTAIN ESTIMATED MARGINAL MEANS (AUTOMATION) - PAIRWISE 
automation_emmeans <- emmeans (glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster, ~ AutomationLevel, type = "response")
automation_emmeans
# PAIRWISE
pairwise_automation <- pairs (automation_emmeans, type = "response", adjust = "bonferroni")
pairwise_automation
```

##### Explanation (Level of Automation)

-   L2 automation decreased glance time towards the instrument cluster by 84 % (e^(-1.83) ~ 0.16), compared to manual driving (L2 automation: EMM = 1.17, 95 % CI [0.96, 1.43]; Manual Driving: EMM = 7.33, 95 % CI [6.42, 8.37].



#### Interaction Effect (Automation\*Lighting)

```{r}
# OBTAIN ESTIMATED MARGINAL MEANS (AUTOMATION*LIGHTTING) - PAIRWISE 
interaction_automation_lighting_emmeans <- emmeans (glmm_final_model_tweedie_PercentageOfGlanceInstrumentCluster, ~ AutomationLevel*LightingConditions)
interaction_automation_lighting_emmeans

# PAIRWISE
pairwise_interaction <- pairs (interaction_automation_lighting_emmeans, adjust = "bonferroni")
pairwise_interaction
```




